version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: .env
    container_name: api
    restart: unless-stopped
    volumes:
      - ./src:/usr/app/src
      - ./node_modules:/usr/app/node_modules
      - ./package.json:/usr/app/package.json
      - ./views:/usr/app/views
    ports:
      - '${PORT}:${PORT}'
      - '9229:9229'
    depends_on:
      - redis

  redis:
    image: bitnami/redis@sha256:76d250e94bd9d9315a807e8a45adc48091927802d54110187cbaee98a59bc4f1
    env_file: .env
    container_name: redis
    restart: unless-stopped
    ports:
      - '7379:6379'
    volumes:
      - 'redisLocal:/bitnami/redis/data'

  db:
    image: postgres:14-alpine
    env_file: .env
    container_name: db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '6432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: worker
    restart: unless-stopped
    volumes:
      - ./src:/usr/app/src
      - ./node_modules:/usr/app/node_modules
      - ./package.json:/usr/app/package.json
      - ./views:/usr/app/views
    depends_on:
      - db
      - redis
    command: ['/bin/bash', '-c', './entrypoint.sh; pnpm worker:dev']

volumes:
  pgdata:
  redisLocal:
