FROM node:lts-bullseye-slim@sha256:d93fb5c25db163dc795d40eabf66251a2daf6a2c6a2d21cc29930e754aef4c2c

RUN apt-get update -y && apt-get install --no-install-recommends --no-install-suggests -y openssl \
&& apt-get install --no-install-recommends --no-install-suggests -y curl && apt-get install --no-install-recommends --no-install-suggests -y dumb-init \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app

RUN npm config set unsafe-perm true && npm install -g pnpm

COPY package.json pnpm-lock.yaml tsconfig.json ./

RUN npm pkg delete scripts.prepare && pnpm install --frozen-lockfile && pnpm generate

COPY . .

EXPOSE ${PORT}
EXPOSE 9229

RUN chmod +x ./start_dev.sh && chown node:node /usr/app

USER node

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/bin/bash", "-c", "./start_dev.sh"]
