name: CI

on:
  push:
    branches: [main, staging]

jobs:
  ci-workflow:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Pipeline
        run: |
          echo "ci running"
