name: CI

on:
  push:
    branches: [main, staging]

jobs:
  ci-workflow:
    strategy:
      fail-fast: false
      matrix:
        os: [latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Pipeline
        run: |
          echo "ci running"
